# Dependabot will run on day 8 of each month at 03:05 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "5 3 8 * *"
    open-pull-requests-limit: 20
    assignees:
      - "Bannsaenger"
    versioning-strategy: "increase"
